WITH RECURSIVE ECOLI_TREE AS (
  SELECT ID, PARENT_ID, 1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL
  UNION ALL
  SELECT e.ID, e.PARENT_ID, p.GENERATION + 1
  FROM ECOLI_DATA e
  JOIN ECOLI_TREE p ON e.PARENT_ID = p.ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM ECOLI_TREE
WHERE ID NOT IN (
  SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;