-- 코드를 입력하세요
SELECT CCRH.HISTORY_ID, 
TRUNCATE(
    CRCC.DAILY_FEE * (DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1) *
        (1 - COALESCE(CRCDP.DISCOUNT_RATE, 0) / 100)
    , 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
NATURAL JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CCRH 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
AND (
        (DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1 >= 90 AND CRCDP.DURATION_TYPE = '90일 이상') OR
        (DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1 >= 30 AND DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1 < 90 AND CRCDP.DURATION_TYPE = '30일 이상') OR
        (DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1 >= 7 AND DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1 < 30 AND CRCDP.DURATION_TYPE = '7일 이상') OR
        (DATEDIFF(CCRH.END_DATE, CCRH.START_DATE) + 1 < 7 AND CRCDP.DURATION_TYPE IS NULL)
    )
WHERE CRCC.CAR_TYPE = "트럭"
ORDER BY
    FEE DESC, CCRH.HISTORY_ID DESC;